name: 'Create an Open Catalogi page'
author: 'Open Catalogi'
description: 'Creates an Open Catalogi page for a specific organisation'

branding:
  icon: 'file-plus'
  color: 'blue'

inputs:
  github_pages_branch:
    description: 'The banche on wish the github page wil be build'
    required: false
    default: 'gh-pages'
  github_repository_name_as_prefix:
    description: 'Whether to use the github repository name as a prefix, set to false when using a custom domain'
    required: false
    default: 'true'
  repository:
    description: 'The github repository to use (could be an external repository)'
    required: false
    default: ${{ github.event.repository.url }}
  me_url:
    description: 'The me (profile) url used'
    required: false
    default: 'https://api.opencatalogi.nl/api/users/me'
  api_url:
    description: 'The location of the open catalogi api (change if you are running your own api)'
    required: false
    default: 'https://api.opencatalogi.nl/api'
  admin_url:
    description: 'The admin (dashboard) url used'
    required: false
    default: 'https://api.opencatalogi.nl/admin'
  base_url:
    description: 'The BASE location of the open catalogi api (change if you are running your own api)'
    required: false
    default: 'https://api.opencatalogi.nl'
  frontend_url:
    description: 'the location (url) of this open catalogi installation'
    required: false
    default: 'https://api.opencatalogi.nl'
  login_redirect:
    description: 'publiccode.yml path'
    required: false
    default: 'vault'
  admin_dashboard_url:
    description: 'the location of the pen catalogi dashboard'
    required: false
    default: 'https://admin.opencatalogi.nl'
  nl_design_theme_classname:
    description: 'the class name of the desired nl design theme'
    required: false
    default: 'open-webconcept-theme'
  arrow_breadcrumbs:
    description: 'whether to use arrow breadcrums instead of the normal breadcrumbs'
    required: false
    default: 'false'
  navbar_logo:
    description: 'An base64 encoded svg file or url to the logo used in the main menu'
    required: false
    default: 'https://openwebconcept.nl/wp-content/themes/openwebconcept/assets/src/images/logo@2x.png'
  gitname:
    description: 'Git name configuration for bump commit'
    required: false
    default: 'Open Catalogi bot'
  gitmail:
    description: 'Git mail configuration for bump commit'
    required: false
    default: 'bot@opencatalogi.nl'

outputs:
  page:
    description: 'A zip of the build page'

runs:
  using: "composite"
  steps:
    - name: Get the Open Catalogi Web APP
      uses: actions/checkout@v2
      with:
        repository: OpenCatalogi/web-app
        ref: development

    # With special thanxs to https://github.com/SpicyPizza/create-envfile
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_GATSBY_USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX: ${{ inputs.github_repository_name_as_prefix }}
        envkey_GATSBY_GITHUB_REPOSITORY_NAME: ${{ inputs.repository }}
        envkey_GATSBY_ME_URL: ${{ inputs.me_url }}
        envkey_GATSBY_API_URL: ${{ inputs.api_url }}
        envkey_GATSBY_ADMIN_URL: ${{ inputs.admin_url }}
        envkey_GATSBY_BASE_URL: ${{ inputs.base_url }}
        envkey_GATSBY_FRONTEND_URL: ${{ inputs.frontend_url }}
        envkey_GATSBY_LOGIN_REDIRECT: ${{ inputs.login_redirect }}
        envkey_GATSBY_ADMIN_DASHBOARD_URL: ${{ inputs.admin_dashboard_url }}
        envkey_GATSBY_NL_DESIGN_THEME_CLASSNAME: ${{ inputs.nl_design_theme_classname }}
        envkey_GATSBY_ARROW_BREADCRUMBS: ${{ inputs.arrow_breadcrumbs }}
        envkey_GATSBY_HEADER_LOGO_URL: ${{ inputs.navbar_logo }}

        # envkey_GATSBY_GITHUB_ORGANIZATION_URL: ${{ env.GITHUB_ORGANIZATION_URL }}
        directory: pwa/static
        file_name: .env.production
        fail_on_empty: true
        sort_keys: false

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      shell: bash
      run: cd pwa && npm install

    - name: Remove old Gatsby cache
      shell: bash
      run: rm -rf pwa/.cache

    - name: Build application
      shell: bash
      run: cd pwa && npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: ${{ inputs.github_pages_branch }}
        folder: pwa/public

